# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'individualGame1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from interface import displayingData as data


class Ui_IndividualGames(object):
    def __init__(self, awayTeam, homeTeam, fdawayTeamSpread, fdawayTeamSpreadOdds, fdhomeTeamSpread, fdhomeTeamSpreadOdds,
                 fdawayTeamMoney, fdhomeTeamMoney, fdover, fdoverOdds, fdunder, fdunderOdds,
                 dkawayTeamSpread, dkawayTeamSpreadOdds, dkhomeTeamSpread, dkhomeTeamSpreadOdds,
                 dkawayTeamMoney, dkhomeTeamMoney, dkover, dkoverOdds, dkunder, dkunderOdds):
        self.awayTeam = awayTeam
        self.homeTeam = homeTeam
        self.fdawayTeamSpread = fdawayTeamSpread
        self.fdawayTeamSpreadOdds = fdawayTeamSpreadOdds
        self.fdhomeTeamSpread = fdhomeTeamSpread
        self.fdhomeTeamSpreadOdds = fdhomeTeamSpreadOdds
        self.fdawayTeamMoney = fdawayTeamMoney
        self.fdhomeTeamMoney = fdhomeTeamMoney
        self.fdover = fdover
        self.fdoverOdds = fdoverOdds
        self.fdunder = fdunder
        self.fdunderOdds = fdunderOdds

        self.dkawayTeamSpread = dkawayTeamSpread
        self.dkawayTeamSpreadOdds = dkawayTeamSpreadOdds
        self.dkhomeTeamSpread = dkhomeTeamSpread
        self.dkhomeTeamSpreadOdds = dkhomeTeamSpreadOdds
        self.dkawayTeamMoney = dkawayTeamMoney
        self.dkhomeTeamMoney = dkhomeTeamMoney
        self.dkover = dkover
        self.dkoverOdds = dkoverOdds
        self.dkunder = dkunder
        self.dkunderOdds = dkunderOdds

    def setupUi(self, IndividualGames):
        IndividualGames.setObjectName("IndividualGames")
        IndividualGames.resize(800, 605)
        self.centralwidget = QtWidgets.QWidget(IndividualGames)
        # self.centralwidget.setStyleSheet("""
        #     QWidget{
        #         background-color:rgb(0,0,0);
        #         }
        #         """)
        self.centralwidget.setObjectName("centralwidget")

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(260, 70, 311, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)

        # self.tableWidget.setStyleSheet("""
        #         QTableWidget{
        #             background-color:rgb(255,255,255);
        #             }
        #             """)
        self.tableWidget.setGeometry(QtCore.QRect(20, 140, 381, 101))
        self.tableWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.tableWidget.setMaximumSize(QtCore.QSize(711, 16777215))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)

        self.tableWidget_2.setGeometry(QtCore.QRect(20, 300, 381, 101))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        IndividualGames.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IndividualGames)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        IndividualGames.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IndividualGames)
        self.statusbar.setObjectName("statusbar")
        IndividualGames.setStatusBar(self.statusbar)

        self.retranslateUi(IndividualGames)
        QtCore.QMetaObject.connectSlotsByName(IndividualGames)

    def retranslateUi(self, IndividualGames):
        _translate = QtCore.QCoreApplication.translate
        IndividualGames.setWindowTitle(_translate("IndividualGames", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("IndividualGames", "This is for the individual games - to show their history\n"
""))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("IndividualGames", self.awayTeam))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("IndividualGames", self.homeTeam))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("IndividualGames", "Spread"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("IndividualGames", "MoneyLine"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("IndividualGames", "Over/Under"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("IndividualGames", self.fdawayTeamSpread))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("IndividualGames", self.fdawayTeamMoney))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("IndividualGames", self.fdover))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("IndividualGames", self.fdhomeTeamSpread))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("IndividualGames", self.fdhomeTeamMoney))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("IndividualGames", self.fdunder))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("IndividualGames", "FanDuel"))
        self.label_2.setText(_translate("IndividualGames", "DraftKings"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("IndividualGames", self.awayTeam))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("IndividualGames", self.homeTeam))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("IndividualGames", "Spread"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("IndividualGames", "MoneyLine"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("IndividualGames", "Over/Under"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("IndividualGames", self.dkawayTeamSpread))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("IndividualGames", self.dkawayTeamMoney))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("IndividualGames", self.dkover))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("IndividualGames", self.dkhomeTeamSpread))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("IndividualGames", self.dkhomeTeamMoney))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("IndividualGames", self.dkunder))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     IndividualGames = QtWidgets.QMainWindow()
#     ui = Ui_IndividualGames()
#     ui.setupUi(IndividualGames)
#     IndividualGames.show()
#     sys.exit(app.exec_())

"""
This is the function that will get called whenever the user clicks to view more detail
about an individual game. This function will create a window by generating an instance of the 
individualGames class, giving it the parameters that it needs for games, by calling the functions that 
are contained in the displayingData.py file. Those function calls will return values that will be passed
into the instantiation of the object.

Calls using the 'Data' identifier are just calling the displayingData.py file - that is how it was imported
into this file.

The gameID will be able to be provided because this function will only get called when a game is already specified 
and the gameId will be known when it is specified, and therefore it can be passed to this function call 

"""

def decidingWindow(gameID):
    style = """
            QTableWidget{
                background-color: white;
                }
            CentralWidget{
                background-color: rgb(255,255);
                }
            
            """

    homeTeam, awayTeam = data.gettingTeams(gameID)

    # Getting the spread data for the home teams - homeTeams is abbreviated to HT
    HTfdSpread, HTfdSpreadOdds, HTdkSpread, HTdkSpreadOdds = data.gettingSpreadInfo(gameID, homeTeam)
    # Getting the spread data for the away teams - homeTeams is abbreviated to AT
    ATfdSpread, ATfdSpreadOdds, ATdkSpread, ATdkSpreadOdds = data.gettingSpreadInfo(gameID, awayTeam)

    # Getting the moneyline data for both the home and awayTeam
    fdHomeMoney, fdAwayMoney, dkHomeMoney, dkAwayMoney = data.gettingMoneyLineInfo(gameID)

    # Getting the over/unders and their odds
    fdOver, fdOverOdds, fdUnder, fdUnderOdds, dkOver, dkOverOdds, dkUnder, dkUnderOdds = data.gettingOverUnder(gameID)

    # Now creating an instance of the UI class - while giving it the parameters that those variable receieved.






    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(style)
    IndividualGames = QtWidgets.QMainWindow()
    ui = Ui_IndividualGames(awayTeam, homeTeam, ATfdSpread, ATfdSpreadOdds, HTfdSpread, HTfdSpreadOdds, fdAwayMoney, fdHomeMoney, fdOver,
                            fdOverOdds, fdUnder, fdUnderOdds, ATdkSpread, ATdkSpreadOdds, HTdkSpread, HTdkSpreadOdds, dkAwayMoney, dkHomeMoney,
                            dkOver, dkOverOdds, dkUnder, dkUnderOdds)
    ui.setupUi(IndividualGames)
    IndividualGames.show()
    sys.exit(app.exec_())



decidingWindow(12568)